# File: configs/config.yaml

database:
  dsn:  "irit.db" 
  # msyql: "root:sch!ADV25_kel2@tcp(127.0.0.1:3306)/irits_db?charset=utf8mb4&parseTime=True&loc=Local"

server:
  url: "0.0.0.0:8080"

jwt:
  secret: "rahasia123"